version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: edr
      POSTGRES_PASSWORD: supersecure
      POSTGRES_DB: edr_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgres://edr:supersecure@postgres:5432/edr_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pg_data:
