"""Generate the Obsidian-compatible vault from records and extracted facts.

Everything under ``atlas/vault/`` is generated by this file: delete the directory
and this rebuilds it. Notes carry stable ids in their filenames and link back to
the record or extracted entry they came from. Authored analyst material lives in
``atlas/authored/`` and is rendered under ``_authored/`` with a visible banner; a
generated note may LINK to an authored one, never absorb it.

Evidence labels are rendered exactly as recorded. Nothing here promotes a
static_inference to a direct_reference, an executed_transformation to an
observation, or a documented claim to an observed one.
"""
from __future__ import annotations

import collections
import gzip
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parents[0] / "src"))
from modcheck import yamlio  # noqa: E402
from modcheck.store import Store  # noqa: E402

EXTRACTED = ROOT / "extracted"
VAULT = ROOT / "vault"
AUTHORED = ROOT / "authored"
# A typed reference: dot-separated segments, never ending in a dot. Shared with validate.py.
REF_PATTERN = r"\b(mechanism|question|workflow|event|type|source|extracted|record|request|scenario):([A-Za-z0-9_/#$-]+(?:\.[A-Za-z0-9_/#$-]+)*)"

GENERATED = ("> [!info] Generated\n> Built by `atlas/extract/vault.py` from the records and "
             "extracted facts it links to. Do not edit; edit the source and regenerate.\n\n")
AUTHORED_BANNER = ("> [!warning] Analyst-authored\n> Interpretation, not extraction. Claims "
                   "cite evidence ids; anything uncited is opinion. Reviewed corrections go "
                   "into the store records or the extractors, never into a generated note.\n\n")
ACC = {0x0001: "public", 0x0002: "private", 0x0004: "protected", 0x0008: "static", 0x0010: "final",
       0x0400: "abstract", 0x0100: "native", 0x1000: "synthetic"}


def slug(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", text).strip("_")[:120]


def link(target: str, label: str | None = None) -> str:
    return f"[[{target}|{label}]]" if label else f"[[{target}]]"


def write(path: Path, body: str, generated: bool = True) -> None:
    """Write a note: frontmatter first (Obsidian requires it at byte 0), then the banner."""
    path.parent.mkdir(parents=True, exist_ok=True)
    banner = GENERATED if generated else AUTHORED_BANNER
    if body.startswith("---\n") and "\n---\n" in body[4:]:
        head, _, rest = body[4:].partition("\n---\n")
        body = "---\n" + head + "\n---\n\n" + banner + rest.lstrip("\n")
    else:
        body = banner + body
    path.write_text(body)


def fm(**fields) -> str:
    lines = ["---"]
    for k, v in fields.items():
        if isinstance(v, (list, tuple)):
            lines.append(f"{k}:")
            lines += [f"  - {json.dumps(x)}" for x in v]
        else:
            lines.append(f"{k}: {json.dumps(v)}")
    lines.append("---")
    return "\n".join(lines) + "\n\n"


def pkg_of(internal_or_dotted: str) -> str:
    """Depth-4 package of a class (`net.minecraft.world.level` for `net/minecraft/world/level/Level$1`)."""
    dotted = internal_or_dotted.replace("/", ".")
    return ".".join(dotted.split(".")[:-1][:4])


def full_pkg(internal: str) -> str:
    return internal.rsplit("/", 1)[0].replace("/", ".") if "/" in internal else "(default)"


def access_words(access: int) -> str:
    return " ".join(w for bit, w in ACC.items() if access & bit)


def short(dotted: str) -> str:
    return dotted.replace("/", ".").split(".")[-1]


# ---------------------------------------------------------------------------
class Atlas:
    def __init__(self) -> None:
        self.corpus = json.loads((EXTRACTED / "corpus.json").read_text())
        self.fabric = json.loads((EXTRACTED / "fabric_api.json").read_text())
        self.registries = json.loads((EXTRACTED / "minecraft_registries.json").read_text())
        self.edges = json.loads((EXTRACTED / "edges.json").read_text())
        self.env = json.loads((EXTRACTED / "resolved_environment.json").read_text())
        with gzip.open(EXTRACTED / "minecraft_surface.json.gz", "rt") as fh:
            self.surface = json.load(fh)
        tpath = EXTRACTED / "mixin_transformation_tests.json"
        self.transform = json.loads(tpath.read_text()) if tpath.exists() else None
        self.store = Store()
        self.pack = self.store.pack("minecraft")
        self.workflows = self._load_authored("workflows")
        self.questions = self._load_authored("questions")
        self.systems = self._load_authored("systems")
        self.requests = self._load_authored("requests")
        self.contracts = self._load_authored("contracts")
        self.written: list[Path] = []
        self.note_index: set[str] = set()

    def _load_authored(self, kind: str) -> list[dict]:
        out = []
        for path in sorted((AUTHORED / kind).glob("*.yaml")):
            data = yamlio.load_path(path)
            for entry in (data if isinstance(data, list) else [data]):
                entry["_path"] = str(path.relative_to(ROOT))
                out.append(entry)
        return out

    def put(self, rel: str, body: str, generated: bool = True) -> str:
        path = VAULT / rel
        write(path, body, generated)
        self.written.append(path)
        self.note_index.add(rel[:-3] if rel.endswith(".md") else rel)
        return rel[:-3] if rel.endswith(".md") else rel

    # -- indexes ------------------------------------------------------------
    def hooked_types(self) -> dict[str, list[dict]]:
        """vanilla internal name -> edges whose `to` endpoint lives in that type (injections, calls, reads, writes)."""
        idx: dict[str, list[dict]] = collections.defaultdict(list)
        for e in self.edges["edges"]:
            to = e["to"]
            if to["kind"] in ("registry", "event"):
                continue
            owner = to.get("owner") or (to["id"] if to["kind"] == "type" else None)
            if owner and owner.replace(".", "/").startswith(("net/minecraft/", "com/mojang/")):
                idx[owner.replace(".", "/")].append(e)
        return idx

    def events(self) -> dict[str, dict]:
        ev: dict[str, dict] = {}
        for e in self.edges["edges"]:
            if e["relation"] == "callback_of":
                ev.setdefault(e["to"]["id"], {"callback": None, "publishers": [], "module": e.get("module")})
                ev[e["to"]["id"]]["callback"] = e["from"]["id"]
            elif e["relation"] == "publishes_event":
                ev.setdefault(e["to"]["id"], {"callback": None, "publishers": [], "module": e.get("module")})
                ev[e["to"]["id"]]["publishers"].append(e)
        return ev

    def injection_edges(self) -> list[dict]:
        return [e for e in self.edges["edges"] if e["relation"] in ("injects_into", "wraps", "replaces")]

    def handler_sites(self) -> dict[tuple, list[dict]]:
        """(handler owner, handler name) -> injection edges of that handler."""
        idx: dict[tuple, list[dict]] = collections.defaultdict(list)
        for e in self.injection_edges():
            idx[(e["from"].get("owner"), e["from"]["id"])].append(e)
        return idx

    def type_link(self, internal_or_dotted: str, label: str | None = None) -> str:
        dotted = internal_or_dotted.replace("/", ".")
        rel = f"40-Interfaces/{slug(dotted)}"
        if rel in self.note_index:
            return link(rel, label or short(dotted))
        return f"`{label or dotted}`"

    # -- generation ---------------------------------------------------------
    def build(self) -> None:
        for child in VAULT.iterdir() if VAULT.exists() else []:
            shutil.rmtree(child) if child.is_dir() else child.unlink()
        self.interfaces()          # first: other notes link to interface notes only if they exist
        self.scope()
        self.systems_notes()
        self.mechanisms()
        self.interactions()
        self.failures()
        self.workflow_notes()
        self.request_notes()
        self.question_notes()
        self.coverage()
        self.index()

    # -- 00 scope -------------------------------------------------------------
    def scope(self) -> None:
        c = self.corpus
        mc = c["minecraft"]
        v = mc["version_json"]
        env = self.env
        on_rt = {e["path"] for e in env["configurations"].get("runtimeClasspath", [])}
        on_cp = {e["path"] for e in env["configurations"].get("compileClasspath", [])}
        rows = ["| group | artifact | version | classes (top/nested) | compile | runtime | sha256 |", "|---|---|---|---|---|---|---|"]
        for a in sorted(c["artifacts"], key=lambda a: (a["group"], a["name"])):
            rows.append(f"| {a['group']} | {a['name']} | {a['version']} | {a['classes_top_level']}/{a['classes_nested']} | "
                        f"{'yes' if a['path'] in on_cp else ''} | {'yes' if a['path'] in on_rt else ''} | `{a['sha256'][:16]}` |")
        body = fm(type="scope", generated_at=c["generated_at"]) + "# Corpus: what was actually resolved\n\n"
        body += ("This is the concrete input set. Every fact in the atlas that is marked "
                 "`direct_reference` or `static_inference` was read from one of these files, "
                 "identified by hash. Anything not listed here is outside the corpus, and the "
                 f"atlas says so in {link('00-Scope/Branches', 'Branches')}.\n\n")
        body += f"**Source of truth:** {c['source_of_truth']}\n\n"
        body += ("## Minecraft Java Edition 26.3 -- pinned identity\n\n"
                 f"- version id `{v['id']}`, world version {v['world_version']}, protocol {v['protocol_version']}\n"
                 f"- Java {v['java_version']}\n"
                 f"- resource pack format {v['pack_version']['resource_major']}.{v['pack_version']['resource_minor']}, "
                 f"data pack format {v['pack_version']['data_major']}.{v['pack_version']['data_minor']}\n"
                 f"- stable: {v['stable']}\n\n")
        proc = env["minecraft_jar_processing"]
        body += ("## Cache inventory versus the resolved environment\n\n"
                 "Two different things, kept apart. The **cache inventory** is every jar in the Gradle caches "
                 "that this project's tooling downloaded. The **resolved environment** is what the reference "
                 f"project's own Gradle build put on its classpaths (`extracted:resolved_environment.json`, "
                 f"{env['method']}).\n\n"
                 f"| configuration | entries |\n|---|---|\n" + "\n".join(f"| {k} | {n} |" for k, n in env["counts"].items()) + "\n\n"
                 f"- corpus artifacts on the runtime classpath: {env['corpus_artifacts_on_runtime_classpath']} / {env['corpus_artifacts_total']}\n"
                 f"- runtime entries outside the corpus: {env['runtime_entries_not_in_corpus']}\n\n"
                 "### The jar a mod compiles against is not Mojang's jar\n\n"
                 f"The compile classpath carries a Loom-processed jar (`{Path(proc['processed_jar']['path']).name}`, "
                 f"sha256 `{proc['processed_jar']['sha256'][:16]}`), not the merged cache jar (`{Path(proc['cache_jar']['path']).name}`, "
                 f"`{proc['cache_jar']['sha256'][:16]}`). Same {proc['entries_processed']} entries; "
                 f"{proc['classes_with_different_bytes']} classes differ: {len(proc['member_access_changes'])} member access "
                 f"changes, {len(proc['class_access_changes'])} class access changes, {len(proc['hierarchy_changes'])} "
                 f"hierarchy changes (interfaces injected). Details: {link('00-Scope/Processed_Jar_Diff')}. Every member "
                 "resolution in the atlas is against the processed jar, because that is what a mod resolves against; "
                 "which module widened what is question:q.processed_jar_change_provenance.\n\n")
        body += f"## Artifacts ({len(c['artifacts'])})\n\n" + "\n".join(rows) + "\n\n"
        body += "## Groups\n\n" + "\n".join(f"- **{g}**: {n}" for g, n in sorted(c["groups"].items())) + "\n"
        self.put("00-Scope/Corpus.md", self._render_ref(body))

        b = fm(type="scope") + "# Processed jar versus cache jar\n\n"
        b += ("What Loom did to Mojang's merged jar before the reference project compiled against it. "
              "`from`/`to` are JVM access flags.\n\n## Hierarchy changes (interfaces injected)\n\n| class | interfaces added |\n|---|---|\n")
        for h in proc["hierarchy_changes"]:
            b += f"| {self.type_link(h['class'])} | {', '.join('`' + i + '`' for i in h['interfaces_added'])} |\n"
        b += "\n## Class access changes\n\n| class | from | to |\n|---|---|---|\n"
        for h in proc["class_access_changes"]:
            b += f"| {self.type_link(h['class'])} | {access_words(h['from'])} | {access_words(h['to'])} |\n"
        b += f"\n## Member access changes ({len(proc['member_access_changes'])})\n\n| class | member | from | to |\n|---|---|---|---|\n"
        for h in proc["member_access_changes"]:
            b += f"| {self.type_link(h['class'])} | `{h['member']}{h['desc'] if h['desc'].startswith('(') else ''}` | {access_words(h['from'])} | {access_words(h['to'])} |\n"
        self.put("00-Scope/Processed_Jar_Diff.md", b)

        self.put("00-Scope/Branches.md", fm(type="scope") + (Path(AUTHORED / "branches.md").read_text()
                 if (AUTHORED / "branches.md").exists() else "# Branches\n\n(no authored branch inventory yet)\n"), generated=False)

        body = fm(type="scope") + "# Data-driven surface shipped in the 26.3 jar\n\n"
        body += ("Everything under `data/minecraft/<type>/` is a data pack the game ships with "
                 "itself. Each type is a modification mechanism that needs no Java: a data pack "
                 "adding or overriding entries here changes the game. Counts are the vanilla "
                 "entries, read from the jar.\n\n| type | vanilla entries |\n|---|---|\n")
        body += "\n".join(f"| `{t}` | {n} |" for t, n in mc["data_entries_by_type"].items())
        body += "\n\n## Assets (resource pack) shipped in the jar\n\n| type | entries |\n|---|---|\n"
        body += "\n".join(f"| `{t}` | {n} |" for t, n in mc["asset_entries_by_type"].items())
        self.put("00-Scope/Data_Driven_Surface.md", body)

        body = fm(type="scope") + "# Source coverage (minecraft pack)\n\n"
        body += "| id | kind | cached | licence |\n|---|---|---|---|\n"
        for sid, s in sorted(self.pack.sources.items()):
            body += f"| `{sid}` | {s.get('kind')} | {'yes' if s.get('evidence_path') else 'no'} | {s.get('license', '?')} |\n"
        self.put("00-Scope/Sources.md", body)

    # -- 20 systems -------------------------------------------------------------
    def systems_notes(self) -> None:
        hooked = self.hooked_types()
        by_pkg: dict[str, list[str]] = collections.defaultdict(list)
        for t in hooked:
            by_pkg[pkg_of(t)].append(t)
        authored = {s["id"]: s for s in self.systems}
        pk = self.surface["packages"]
        # roll the full-package inventory up to depth 4
        depth4: dict[str, dict] = collections.defaultdict(lambda: {"classes": 0, "top_level": 0, "differs": 0, "subpackages": set()})
        for pkg, n in pk.items():
            d4 = ".".join(pkg.split(".")[:4])
            depth4[d4]["classes"] += n["classes"]
            depth4[d4]["top_level"] += n["top_level"]
            depth4[d4]["differs"] += n["differs"]
            depth4[d4]["subpackages"].add(pkg)
        body = fm(type="index") + "# Game systems (by package)\n\n"
        body += ("The declared inventory of the jar a mod compiles against: every class, hooked or not "
                 f"(`extracted:minecraft_surface.json.gz`: {self.surface['counts']['classes']} classes, "
                 f"{self.surface['counts']['members']} members, {self.surface['counts']['packages']} packages, rolled up "
                 "to depth 4 here). `hooked types` counts classes in the package that at least one Fabric API module "
                 "injects into, wraps, calls, reads or writes; a zero means no shipped module touches it, not that "
                 "it cannot be modified. `processed` counts classes Loom changed before compilation.\n\n"
                 "| package | classes | top-level | processed | hooked types | note |\n|---|---|---|---|---|---|\n")
        for pkg in sorted(set(depth4) | set(authored)):
            d = depth4.get(pkg, {"classes": 0, "top_level": 0, "differs": 0, "subpackages": set()})
            n_h = len(by_pkg.get(pkg, []))
            note = link(f"20-Systems/{slug(pkg)}", "note")
            body += f"| `{pkg}` | {d['classes']} | {d['top_level']} | {d['differs']} | {n_h} | {note} |\n"
        self.put("20-Systems/_index.md", self._render_ref(body))

        for sysrec in self.systems:
            b = fm(type="system_note", id=sysrec["id"], side=sysrec["side"]) + f"# {sysrec['title']}\n\n"
            b += f"Package `{sysrec['id']}` -- generated view: {link('20-Systems/' + slug(sysrec['id']), 'inventory and hooked types')}\n\n"
            b += f"**Responsibility.** {sysrec['responsibility'].strip()}\n\n**Side.** {sysrec['side']}\n\n"
            b += f"**Threads.** {self._render_ref(sysrec['threads'].strip())}\n\n"
            if sysrec.get("persistence"):
                b += f"**Persistence.** {self._render_ref(sysrec['persistence'].strip())}\n\n"
            for key, title in (("extension_points", "Extension points"), ("interactions", "Interactions to expect"),
                               ("evidence", "Evidence"), ("questions", "Open questions")):
                if sysrec.get(key):
                    b += f"## {title}\n\n" + "\n".join(f"- {self._render_ref(i)}" for i in sysrec[key]) + "\n\n"
            self.put(f"_authored/systems/{slug(sysrec['id'])}.md", b, generated=False)

        classes = self.surface["classes"]
        for pkg in sorted(set(depth4) | set(authored)):
            d = depth4.get(pkg, {"classes": 0, "top_level": 0, "differs": 0, "subpackages": set()})
            types = by_pkg.get(pkg, [])
            b = fm(type="system", package=pkg) + f"# {pkg}\n\n"
            if pkg in authored:
                b += f"Analyst note: {link('_authored/systems/' + slug(pkg), authored[pkg]['title'])}\n\n"
            b += (f"{d['classes']} classes ({d['top_level']} top-level) across {len(d['subpackages'])} packages in the "
                  f"processed jar; {d['differs']} changed by Loom processing; {len(types)} hooked by Fabric API.\n\n")
            if types:
                b += "## Hooked types\n\n"
                for t in sorted(types):
                    rel = collections.Counter(e["relation"] for e in hooked[t])
                    mods = sorted({e.get("module") for e in hooked[t] if e.get("module")})
                    b += f"- {self.type_link(t)} -- " + ", ".join(f"{k}:{v}" for k, v in sorted(rel.items())) + f" -- by {', '.join(mods)}\n"
                b += "\n"
            b += "## Declared inventory\n\n"
            for sub in sorted(d["subpackages"]):
                names = sorted(k for k in classes if full_pkg(k) == sub and "$" not in k)
                if not names:
                    continue
                b += f"### `{sub}` ({len(names)} top-level)\n\n"
                b += ", ".join(self.type_link(n, short(n)) if f"40-Interfaces/{slug(n.replace('/', '.'))}" in self.note_index
                               else f"`{short(n)}`" for n in names) + "\n\n"
            self.put(f"20-Systems/{slug(pkg)}.md", b)

    # -- 30 mechanisms -----------------------------------------------------------
    def mechanisms(self) -> None:
        body = fm(type="index") + "# Modification mechanisms\n\n"
        body += ("Four families, kept apart because they compose differently:\n\n"
                 "1. **Data packs / resource packs** -- no code. See "
                 f"{link('00-Scope/Data_Driven_Surface', 'the data-driven surface')}.\n"
                 f"2. **Registries** -- code registers new content. See {link('30-Mechanisms/Registries')}.\n"
                 "3. **Fabric API modules** -- events, hooks and helpers, each implemented by "
                 "mixins into vanilla. Listed below with what each actually hooks.\n"
                 "4. **Direct mixins by a mod** -- the same mechanism Fabric API uses, applied by "
                 f"a mod itself. See {link('30-Mechanisms/Mixin')} and {link('30-Mechanisms/Transformation_Tests', 'the transformation tests')}.\n\n")
        body += "| module | lifecycle | env | mixins | injections | by injector | events published | api classes |\n|---|---|---|---|---|---|---|---|\n"
        by_mod: dict[str, list[dict]] = collections.defaultdict(list)
        for e in self.edges["edges"]:
            if e.get("module"):
                by_mod[e["module"]].append(e)
        for m in sorted(self.fabric["modules"], key=lambda m: m["id"]):
            lifecycle = ((m["declared"].get("custom") or {}).get("fabric-api:module-lifecycle", "?"))
            env = m["declared"].get("environment") or "*"
            es = by_mod.get(m["id"], [])
            inj = [e for e in es if e["relation"] in ("injects_into", "replaces", "wraps")]
            kinds = collections.Counter(e["injector"] for e in inj)
            pub = len({e["to"]["id"] for e in es if e["relation"] == "publishes_event"})
            body += (f"| {link('30-Mechanisms/' + slug(m['id']), m['id'])} | {lifecycle} | {env} | "
                     f"{m['counts']['mixin_classes_found']} | {len(inj)} | {', '.join(f'{k} {v}' for k, v in kinds.most_common())} | {pub} | {m['counts']['api_classes']} |\n")
        self.put("30-Mechanisms/_index.md", body)

        for m in self.fabric["modules"]:
            es = by_mod.get(m["id"], [])
            b = fm(type="mechanism", module=m["id"], version=m["version"], sha256=m["sha256"],
                   lifecycle=(m["declared"].get("custom") or {}).get("fabric-api:module-lifecycle", "?"))
            b += f"# {m['id']}\n\n"
            d = m["declared"]
            b += f"**Version** `{m['version']}` -- **artifact sha256** `{m['sha256']}`\n\n"
            b += "## Declared (fabric.mod.json)\n\n"
            b += f"- environment: `{d.get('environment') or '*'}`\n"
            b += f"- depends: `{json.dumps(d.get('depends'))}`\n"
            if d.get("breaks"):
                b += f"- breaks: `{json.dumps(d.get('breaks'))}`\n"
            b += f"- entrypoints: `{json.dumps(d.get('entrypoints'))}`\n"
            b += f"- mixin configs: `{json.dumps(d.get('mixins'))}`\n"
            if d.get("accessWidener"):
                b += f"- access widener: `{d['accessWidener']}`\n"
            b += (f"- mixin classes: {m['counts']['mixin_classes_found']} found by annotation, "
                  f"{m['counts']['mixin_classes_declared']} declared in configs; extraction failures: {m['counts']['extraction_failures']}\n")
            b += "\n## Events this module publishes\n\n"
            module_events = sorted({e["to"]["id"] for e in es if e["relation"] == "publishes_event"} |
                                   {e["to"]["id"] for e in es if e["relation"] == "callback_of"})
            if module_events:
                for ev in module_events:
                    b += f"- {link('50-Interactions/events/' + slug(ev), ev.split('.')[-2] + '.' + ev.split('.')[-1])}\n"
            else:
                b += "- none found by extraction\n"
            b += ("\n## Vanilla methods this module modifies\n\nOne row per (injection, selector). `resolution` says how "
                  "the selector matched the processed jar; `points` are the @At targets with their own resolution.\n\n"
                  "| vanilla method | descriptor | resolution | injector | points | env | priority | handler |\n|---|---|---|---|---|---|---|---|\n")
            for e in sorted((e for e in es if e["relation"] in ("injects_into", "replaces", "wraps")),
                            key=lambda e: (e["to"]["owner"], e["to"]["id"])):
                pts = "; ".join(f"{p['value']}" + (f" `{p.get('target')}`" if p.get("target") else "")
                                + (f" ({p['resolution']['state']})" if p.get("resolution") else "") for p in e.get("points", []))
                b += (f"| {self.type_link(e['to']['owner'])}.`{e['to']['id']}` | `{e['to'].get('descriptor') or '?'}` | "
                      f"{e['to']['resolution']['state']} | @{e['injector']} | {pts or '-'} | {e['applies_to'].get('environment')} | "
                      f"{e.get('priority')}{'' if e.get('priority_source') == 'annotation' else ' (default)'} | "
                      f"`{short(e['from']['owner'])}.{e['from']['id']}` |\n")
            b += "\n## API surface\n\n"
            for api in sorted(m["api"], key=lambda a: a["fqcn"]):
                b += f"- {link('40-Interfaces/' + slug(api['fqcn']), api['fqcn'].split('.')[-1])} ({api['kind']}, {len(api['members'])} members)\n"
            b += ("\n## What this establishes, and does not\n\n"
                  "- Injection targets, points and API signatures are `direct_reference`: read from the class files.\n"
                  "- Event publication is `static_inference`: a bytecode pattern, labelled as such.\n"
                  "- How two injections compose is `executed_transformation` evidence in "
                  f"{link('30-Mechanisms/Transformation_Tests')}, not established per module.\n"
                  "- Nothing here is `observed`. No game ran.\n")
            self.put(f"30-Mechanisms/{slug(m['id'])}.md", b)

        r = self.registries
        b = fm(type="mechanism", artifact=r["artifact"], sha256=r["sha256"]) + "# Registries\n\n"
        b += (f"Read from `BuiltInRegistries` and `Registries` in the 26.3 jar (`{r['sha256'][:16]}`). "
              "Each built-in registry is a target for `Registry.register`; each key with a "
              "datapack type is also addable from data.\n\n"
              f"## Built-in registries ({len(r['built_in_registries'])})\n\n| registry | element type |\n|---|---|\n")
        for reg in r["built_in_registries"]:
            b += f"| `{reg['field']}` | `{reg['type']}` |\n"
        b += f"\n## Registry keys ({len(r['registry_keys'])})\n\n"
        b += ", ".join(f"`{k['field']}`" for k in r["registry_keys"]) + "\n"
        self.put("30-Mechanisms/Registries.md", b)

        counts = self.edges["counts"]
        inj_kinds = collections.Counter(e["injector"] for e in self.injection_edges())
        b = fm(type="mechanism") + "# Mixin (direct bytecode modification)\n\n"
        b += (f"Fabric API's own mixins in the corpus: {counts.get('injects_into', 0)} `injects_into`, "
              f"{counts.get('wraps', 0)} `wraps` and {counts.get('replaces', 0)} `replaces` edges, by injector: "
              + ", ".join(f"@{k} {v}" for k, v in inj_kinds.most_common()) + ". A mod may use the same mechanism.\n\n"
              f"Resolution of the selectors against the processed jar: {json.dumps(self.edges['resolution_by_relation'].get('injects_into', {}))} "
              f"(injects_into), {json.dumps(self.edges['resolution_by_relation'].get('wraps', {}))} (wraps); "
              f"points: {json.dumps(self.edges['injection_point_resolution'])}.\n\n"
              f"Runtime: `sponge-mixin` and `mixinextras` -- see {link('00-Scope/Corpus')}. Annotation defaults read from the jar: "
              f"`{json.dumps(self.fabric['mixin_runtime']['annotation_defaults']['Mixin'])}`.\n\n"
              f"How injectors compose is not asserted here; it was executed: {link('30-Mechanisms/Transformation_Tests')}.\n\n"
              f"Analyst note: {link('_authored/mechanisms/mixin', 'composition and ordering')}\n")
        self.put("30-Mechanisms/Mixin.md", b)

        if self.transform:
            t = self.transform
            b = fm(type="evidence", evidence_class=t["evidence_class"], mixin=t["runtime"]["mixin_version"]) + "# Mixin transformation tests\n\n"
            b += (f"**Evidence class `{t['evidence_class']}`.** {t['what_this_is']}\n\n"
                  f"- sponge-mixin `{t['runtime']['sponge_mixin']['sha256'][:16]}`, MixinExtras `{t['runtime']['mixinextras']['sha256'][:16]}`, Java {t['runtime']['java']}\n"
                  f"- harness: `{t['runtime']['harness']}`; configs `{'`, `'.join(t['sources']['configs'])}` with `defaultRequire` {t['sources']['config_default_require']}\n\n"
                  "## Static checks on the pinned jar\n\n")
            sc = t["static_checks"]
            b += (f"- `InjectionPoint.checkPriority` default bytecode: `{' '.join(sc['InjectionPoint.checkPriority.default_bytecode'])}` -- {sc['InjectionPoint.checkPriority.reading']}\n"
                  f"- overriders returning true unconditionally: {', '.join(k for k, v in sc['checkPriority_overriders'].items() if v == ['iconst_1', 'ireturn'])}; "
                  f"not overriding: {', '.join(k for k, v in sc['checkPriority_overriders'].items() if v is None)}\n"
                  f"- applicator pass order: {' -> '.join(sc['ApplicatorPass.order'])}\n"
                  f"- `@Mixin` defaults: `{json.dumps(sc['Mixin.annotation_defaults'])}`\n\n## Scenarios\n\n")
            for s in t["scenarios"]:
                b += f"## {s['id']}\n\n**Question.** {s['question']}\n\n**Setup.** {s['setup']}\n\n"
                b += f"- transformed: {s['transformed']}; bytes changed: {s['bytes_changed']}\n"
                b += f"- applied (audit): {', '.join(a.split(':')[-1].split(' from')[0] for a in s['applied'] if a.startswith('apply')) or 'none'}\n"
                if s["transform_error"]:
                    b += f"- transformation error: `{s['transform_error'].split(' <- ')[-1][:400]}`\n"
                if s["run_error"]:
                    b += f"- run error: `{s['run_error'][:300]}`\n"
                b += f"- trace: `{' -> '.join(s['trace']) if s['trace'] else '(not run)'}`\n\n"
            b += ("## Not established here\n\n- Anything about a running Minecraft: no game class, no loader, no Knot classloader was involved.\n"
                  "- Rules for injector pairs not in the scenarios.\n")
            self.put("30-Mechanisms/Transformation_Tests.md", b)

    # -- 40 interfaces ------------------------------------------------------------
    def interfaces(self) -> None:
        hooked = self.hooked_types()
        classes = self.surface["classes"]
        system_pkgs = {".".join(p.split(".")[:4]) for p in self.surface["packages"]} | {s["id"] for s in self.systems}
        wanted = set(hooked)
        # classes the request analyses name explicitly (type: refs) get a note too
        for r in self.requests + self.workflows + self.systems + self.questions:
            for m in re.finditer(REF_PATTERN, json.dumps(r)):
                if m.group(1) == "type" and m.group(2).replace(".", "/") in classes:
                    wanted.add(m.group(2).replace(".", "/"))
        for t in sorted(wanted):
            dotted = t.replace("/", ".")
            es = hooked.get(t, [])
            c = classes.get(t)
            b = fm(type="interface", fqcn=dotted, side="vanilla") + f"# {dotted}\n\n"
            if pkg_of(t) in system_pkgs:
                b += f"System: {link('20-Systems/' + slug(pkg_of(t)), pkg_of(t))}\n\n"
            else:
                b += f"Package `{pkg_of(t)}`: a library outside the Minecraft jar (no system note).\n\n"
            if c:
                b += (f"`{c['kind']}` {access_words(c['access'])}; extends `{c['super']}`; implements "
                      f"{', '.join('`' + i + '`' for i in c['interfaces']) or 'nothing'}; "
                      f"{'**changed by Loom processing** (see ' + link('00-Scope/Processed_Jar_Diff') + ')' if c['processed_differs'] else 'identical to the cache jar'}.\n\n")
            if es:
                b += ("## How Fabric API modules touch this type\n\n| relation | member | descriptor | resolution | operation / site | env | by | evidence |\n|---|---|---|---|---|---|---|---|\n")
                for e in sorted(es, key=lambda e: (e["relation"], e["to"]["id"], e["to"].get("descriptor") or ""))[:400]:
                    op = e.get("operation") or (f"{e['site']['opcode']}@{e['site']['offset']} in `{short(e['from'].get('owner', ''))}.{e['from']['id']}`" if e.get("site") else "")
                    b += (f"| {e['relation']} | `{e['to']['id']}` | `{(e['to'].get('descriptor') or '?')[:70]}` | {e['to'].get('resolution', {}).get('state', '-')} | "
                          f"{op[:90]} | {e['applies_to'].get('environment')} | {link('30-Mechanisms/' + slug(e.get('module', '')), e.get('module', '')) if e.get('module') else ''} | {e['evidence_class']} |\n")
                if len(es) > 400:
                    b += f"\n({len(es) - 400} more edges not listed)\n"
            if c:
                b += (f"\n## Declared members ({len(c['fields'])} fields, {len(c['methods'])} methods, all visibilities)\n\n"
                      f"From the processed jar `{self.surface['jar']['sha256'][:16]}`. Inherited members are not listed; "
                      "the resolver walks them (`inherited_exact`).\n\n```\n")
                for name, desc, access in c["fields"]:
                    b += f"{access_words(access)} {name} : {desc}\n"
                for name, desc, access in c["methods"]:
                    b += f"{access_words(access)} {name}{desc}\n"
                b += "```\n"
            else:
                b += ("\n## Members\n\nNot in the processed Minecraft jar: this type belongs to a library Minecraft "
                      f"depends on (see {link('00-Scope/Corpus')}, group minecraft_library) and its members were not extracted.\n")
            self.put(f"40-Interfaces/{slug(dotted)}.md", b)
        for m in self.fabric["modules"]:
            for api in m["api"] + m["api_nested"]:
                b = fm(type="interface", fqcn=api["fqcn"], module=m["id"], sha256=m["sha256"]) + f"# {api['fqcn']}\n\n"
                b += f"Module: {link('30-Mechanisms/' + slug(m['id']), m['id'])} -- kind: {api['kind']}\n\n```java\n"
                b += "\n".join(api["members"]) + "\n```\n"
                self.put(f"40-Interfaces/{slug(api['fqcn'])}.md", b)
        for api in self.fabric["loader"]["api"]:
            b = fm(type="interface", fqcn=api["fqcn"], module="fabric-loader") + f"# {api['fqcn']}\n\n"
            b += f"fabric-loader {self.fabric['loader']['version']} -- kind: {api['kind']}\n\n```java\n"
            b += "\n".join(api["members"]) + "\n```\n"
            self.put(f"40-Interfaces/{slug(api['fqcn'])}.md", b)
        files = sorted(p.stem for p in (VAULT / "40-Interfaces").glob("*.md"))
        b = fm(type="index") + f"# Exact interfaces ({len(files)})\n\n"
        vanilla = [f for f in files if f.startswith(("net.minecraft", "com.mojang"))]
        fabric = [f for f in files if f.startswith("net.fabricmc")]
        b += f"## Vanilla types hooked by Fabric API or named by an analysis ({len(vanilla)})\n\n" + "\n".join(f"- {link('40-Interfaces/' + f, f)}" for f in vanilla)
        b += f"\n\n## Fabric API and loader types ({len(fabric)})\n\n" + "\n".join(f"- {link('40-Interfaces/' + f, f)}" for f in fabric) + "\n"
        self.put("40-Interfaces/_index.md", b)

    # -- 50 interactions ------------------------------------------------------------
    def interactions(self) -> None:
        events = self.events()
        b = fm(type="index") + "# Interaction contracts\n\n"
        b += ("An edge is a typed relationship with exact endpoints, a resolution state and an evidence class. "
              f"Totals: {json.dumps(self.edges['counts'])}. Evidence: {json.dumps(self.edges['evidence_classes'])}. "
              f"Resolution: {json.dumps(self.edges['resolution_by_relation'])}.\n\n"
              f"- {link('50-Interactions/events/_index', 'Events')} -- what publishes each, and its callback\n"
              f"- {link('50-Interactions/shared_targets', 'Shared targets')} -- vanilla methods more than one module injects into: potential interactions\n"
              f"- {link('50-Interactions/overwrites', 'Overwrites')} -- methods replaced outright\n"
              f"- {link('30-Mechanisms/Transformation_Tests', 'Composition rules')} -- what the transformer does with a pair of injections\n"
              f"- {link('50-Interactions/store_records', 'Curated interaction records')}\n"
              f"- Analyst contracts: {link('_authored/contracts/_index', 'index')}\n")
        self.put("50-Interactions/_index.md", b)

        contracts_by_id = {c["id"]: c for c in self.contracts}
        self.contract_notes(contracts_by_id)
        sites = self.handler_sites()
        eb = fm(type="index") + "# Events\n\n| event | callback | publishers | module | contract |\n|---|---|---|---|---|\n"
        for ev, info in sorted(events.items()):
            eb += (f"| {link('50-Interactions/events/' + slug(ev), ev.split('.')[-2] + '.' + ev.split('.')[-1])} | "
                   f"`{(info['callback'] or '?').split('.')[-1]}` | {len(info['publishers'])} | "
                   f"{link('30-Mechanisms/' + slug(info.get('module') or ''), info.get('module') or '?')} | "
                   f"{link('_authored/contracts/' + slug(ev), 'yes') if f'event:{ev}' in contracts_by_id else 'no'} |\n")
        self.put("50-Interactions/events/_index.md", eb)
        for ev, info in events.items():
            b = fm(type="event", event=ev, callback=info["callback"] or "") + f"# {ev}\n\n"
            b += f"Callback interface: `{info['callback']}`\n\nModule: {link('30-Mechanisms/' + slug(info.get('module') or ''), info.get('module') or '?')}\n\n"
            b += "## Published from\n\n"
            if info["publishers"]:
                b += "| site | vanilla injection (handler's own injects/wraps edges) | environment | evidence |\n|---|---|---|---|\n"
                for p in info["publishers"]:
                    inj = sites.get((p["from"].get("owner"), p["from"]["id"]), [])
                    where = "; ".join(f"{self.type_link(e['to']['owner'])}.`{e['to']['id']}` @{e['injector']} "
                                      + ", ".join(pt['value'] + (' `' + pt['target'] + '`' if pt.get('target') else '') for pt in e.get('points', []))
                                      for e in inj[:3])
                    if not where:
                        where = ("(handler is not itself an injector: fired from a helper or impl method)"
                                 if p["from"]["owner"].startswith("net/fabricmc/fabric/mixin") else "(impl code, not a mixin)")
                    b += (f"| `{short(p['from']['owner'])}.{p['from']['id']}` @{p['site']['offset']} | {where} | "
                          f"{p['applies_to'].get('environment')} | {p['evidence_class']} |\n")
            else:
                b += "- no publisher found by extraction in any class of any module (question:q.event_publishers_missing)\n"
            b += "\n## Contract\n\nWhat a subscriber may assume is NOT established by extraction. "
            if f"event:{ev}" in contracts_by_id:
                b += f"An analyst-stated contract exists: {link('_authored/contracts/' + slug(ev), 'read it')}.\n"
            else:
                b += (f"No analyst has stated one ({link('_authored/contracts/_index', 'contracts')}); "
                      "the callback signature above is all that is known.\n")
            self.put(f"50-Interactions/events/{slug(ev)}.md", self._render_ref(b))

        b = fm(type="index") + "# Shared targets (potential interactions)\n\n"
        b += ("Vanilla methods that more than one Fabric API module injects into, wraps or replaces. "
              "An entry here is a **potential** interaction: whether two entries interfere depends on (1) exact "
              "resolution of both selectors and points, (2) applicability -- both mixins active in the same environment, "
              f"and (3) the transformer's composition rule for that pair of injector effects and priorities "
              f"({link('30-Mechanisms/Transformation_Tests', 'executed scenarios')}). Same-method overlap is not a "
              "conflict; same-point overlap is not yet computed (question:q.injection_points_not_resolved).\n\n"
              "| vanilla method | modules | injector effects | environments | priorities | exactly resolved |\n|---|---|---|---|---|---|\n")
        for s in self.edges["shared_targets"]:
            effects = sorted({x["effect"] for x in s["entries"]})
            envs = sorted({x["environment"] for x in s["entries"]})
            prios = sorted({x["priority"] for x in s["entries"]})
            b += (f"| {self.type_link(s['owner'])}.`{s['method']}{s['descriptor'] or ''}` | {', '.join(s['modules'])} | "
                  f"{', '.join(effects)} | {', '.join(envs)} | {', '.join(map(str, prios))} | {'yes' if s['exactly_resolved'] else 'no'} |\n")
        self.put("50-Interactions/shared_targets.md", self._render_ref(b))

        b = fm(type="index") + "# Overwrites\n\n"
        b += ("`@Overwrite` replaces a vanilla method body. What that does to other mods' injections into the same "
              f"method was executed, not assumed: see {link('30-Mechanisms/Transformation_Tests')} (HEAD/TAIL/RETURN "
              "injections survive; INVOKE-point ones are refused unless they outrank the overwrite).\n\n"
              "| vanilla method | module | mixin | env |\n|---|---|---|---|\n")
        for e in self.edges["edges"]:
            if e["relation"] == "replaces":
                b += (f"| {self.type_link(e['to']['owner'])}.`{e['to']['id']}{e['to'].get('descriptor', '')}` | {e.get('module')} | "
                      f"`{short(e['from']['owner'])}` | {e['applies_to'].get('environment')} |\n")
        self.put("50-Interactions/overwrites.md", b)

        b = fm(type="index") + "# Curated interaction records (store)\n\n"
        recs = self.pack.records("interaction")
        b += "None recorded for minecraft yet.\n" if not recs else ""
        for r in recs:
            b += f"- `{r.id}` -- {r.get('title')} ({r.get('outcome', {}).get('kind')})\n"
        self.put("50-Interactions/store_records.md", b)

    def contract_notes(self, contracts_by_id: dict[str, dict]) -> None:
        b = fm(type="index") + "# Analyst-stated contracts\n\n"
        b += ("Each note separates what is *asserted* (with the basis for it) from what is "
              "*not established*. A contract is an analyst's reading of declared signatures, "
              "bytecode patterns, executed transformation scenarios and cached documentation; it is not a runtime guarantee.\n\n"
              "| subject | kind | asserted | not established |\n|---|---|---|---|\n")
        for cid, c in sorted(contracts_by_id.items()):
            ident = cid.split(":", 1)[1]
            b += f"| {link('_authored/contracts/' + slug(ident), ident.split('.')[-2] + '.' + ident.split('.')[-1] if '.' in ident else ident)} | {c['kind']} | {len(c['asserted'])} | {len(c['not_established'])} |\n"
        self.put("_authored/contracts/_index.md", b, generated=False)
        for cid, c in contracts_by_id.items():
            ident = cid.split(":", 1)[1]
            b = fm(type="contract", subject=cid, kind=c["kind"]) + f"# Contract: {ident}\n\n"
            b += f"Subject: {self._render_ref(cid)}\n\n## Asserted\n\n| claim | basis | evidence |\n|---|---|---|\n"
            for a in c["asserted"]:
                b += f"| {self._render_ref(a['claim'])} | `{a['basis']}` | {'; '.join(self._render_ref(e) for e in a['evidence'])} |\n"
            b += "\n## Not established\n\n" + "\n".join(f"- {self._render_ref(n)}" for n in c["not_established"]) + "\n\n"
            b += "## Evidence\n\n" + "\n".join(f"- {self._render_ref(e)}" for e in c["evidence"]) + "\n"
            if c.get("questions"):
                b += "\n## Open questions\n\n" + "\n".join(f"- {self._render_ref(q)}" for q in c["questions"]) + "\n"
            self.put(f"_authored/contracts/{slug(ident)}.md", b, generated=False)

    # -- 60 failures --------------------------------------------------------------
    def failures(self) -> None:
        b = fm(type="index") + "# Known failures and resolutions (store records)\n\n"
        for r in self.pack.records("failure"):
            b += f"## {r.id}\n\n**{r.get('title')}**\n\n- symptom: {r.get('symptom')}\n- mechanism: {r.get('mechanism')}\n"
            det = r.get("detector") or {}
            b += f"- detectable: {det.get('detectable')} via `{det.get('check_id')}`\n"
            for res in r.get("resolutions") or []:
                b += f"- resolution: {res}\n"
            b += "\n"
        b += "## Resolutions\n\n"
        for r in self.pack.records("resolution"):
            b += f"- `{r.id}` -- {r.get('title')} (method: {r.get('method')})\n"
        self.put("60-Failures/_index.md", b)

    # -- 10 workflows ------------------------------------------------------------
    def workflow_notes(self) -> None:
        b = fm(type="index") + "# Modder workflows and request families\n\n"
        b += ("Authored. Each family traces intent -> tools today -> decisions -> information -> "
              "automation -> remaining work -> ModCheck's contribution, and names the evidence "
              "each 'today' claim rests on.\n\n| area | family | inventoried | inspected | contract-mapped | analysed | in ModCheck |\n|---|---|---|---|---|---|---|\n")
        for w in sorted(self.workflows, key=lambda w: (w["area"], w["id"])):
            s = w["status"]
            tick = lambda v: "yes" if v else "no"  # noqa: E731
            b += (f"| {w['area']} | {link('10-Workflows/' + slug(w['id']), w['title'])} | {tick(s['inventoried'])} | "
                  f"{tick(s['mechanically_inspected'])} | {tick(s['contract_mapped'])} | "
                  f"{tick(s['interaction_analysed'])} | {tick(s['implemented_in_modcheck'])} |\n")
        self.put("10-Workflows/_index.md", b)
        for w in self.workflows:
            b = fm(type="workflow", id=w["id"], area=w["area"]) + f"# {w['title']}\n\n"
            b += f"**Intent.** {w['intent'].strip()}\n\n"
            for key, title in (("preserve", "Must be preserved"), ("mechanisms", "Mechanisms that can serve it"),
                               ("tools_today", "Tools and artifacts used today"),
                               ("decisions", "Decisions the creator must make"),
                               ("information_needed", "Information those decisions need"),
                               ("automation_existing", "Existing automation"),
                               ("remaining_manual", "Remaining manual or unsupported work"),
                               ("modcheck_contribution", "ModCheck's contribution"),
                               ("interactions_to_check", "Interactions to check"),
                               ("evidence", "Evidence"), ("questions", "Open questions")):
                items = w.get(key) or []
                if items:
                    b += f"## {title}\n\n" + "\n".join(f"- {self._render_ref(str(i))}" for i in items) + "\n\n"
            s = w["status"]
            b += ("## Status\n\n" + "\n".join(f"- {k}: {v}" for k, v in s.items()) + "\n")
            self.put(f"10-Workflows/{slug(w['id'])}.md", b, generated=False)

    def _render_ref(self, text: str) -> str:
        def repl(m):
            kind, ident = m.group(1), m.group(2)
            if kind == "mechanism":
                return link("30-Mechanisms/" + slug(ident), ident)
            if kind == "question":
                return link("80-Unresolved/" + slug(ident), ident)
            if kind == "workflow":
                return link("10-Workflows/" + slug(ident), ident)
            if kind == "event":
                return link("50-Interactions/events/" + slug(ident), ident.split(".")[-1])
            if kind == "type":
                return self.type_link(ident)
            if kind == "source":
                return f"{link('00-Scope/Sources', ident)}"
            if kind == "extracted":
                return f"`extracted/{ident}`"
            if kind == "record":
                return f"`{ident}`"
            if kind == "request":
                return link("70-Requests/" + slug(ident), ident)
            if kind == "scenario":
                return link(f"30-Mechanisms/Transformation_Tests#{ident}", f"scenario {ident}")
            return m.group(0)
        return re.sub(REF_PATTERN, repl, text)

    # -- 70 requests -----------------------------------------------------------------
    def request_notes(self) -> None:
        b = fm(type="index") + "# Request-specific impact analyses\n\n"
        b += ("Each analysis is bound to a canonical request record. A creator request names the record's path and "
              "hash (the validator re-checks it); an analyst exercise says so and carries no approved intent.\n\n"
              "| analysis | canonical request | kind | family |\n|---|---|---|---|\n")
        for r in self.requests:
            cr = r["canonical_request"]
            b += (f"| {link('70-Requests/' + slug(r['id']), r['title'])} | `{cr['id']}`"
                  f"{' (' + cr['path'] + ')' if cr.get('path') else ''} | {cr['kind']} | {self._render_ref(r.get('family', ''))} |\n")
        self.put("70-Requests/_index.md", b)
        for r in self.requests:
            cr = r["canonical_request"]
            b = fm(type="request", id=r["id"], canonical=cr["id"], kind=cr["kind"], family=r.get("family")) + f"# {r['title']}\n\n"
            b += f"**Canonical request.** `{cr['id']}` ({cr['kind']})"
            if cr.get("path"):
                b += f", `{cr['path']}`, sha256 `{cr['sha256'][:16]}`"
                if cr.get("revision_of"):
                    b += f", revision of `{cr['revision_of']}`"
            if cr.get("requirement_ids"):
                b += f"; requirements: {', '.join('`' + x + '`' for x in cr['requirement_ids'])}"
            b += "\n\n"
            if r.get("analyst_exercise"):
                b += "> [!note] Analyst exercise\n> No creator wrote this request. Nothing in it is approved intent.\n\n"
            for key, title in (("request", "Request"), ("approved_behaviour", "Approved behaviour (the request's own words or acceptance criteria)"),
                               ("proposed_contract", "Proposed contract (implementer's decisions, not creator intent)"),
                               ("analyst_assumptions", "Analyst assumptions"),
                               ("preserve", "Preservation obligations"), ("affected_systems", "Affected systems"),
                               ("candidates", "Implementation candidates"), ("dependencies", "Data / control / state dependencies"),
                               ("interactions", "Interactions with the selected environment"),
                               ("alternatives", "Alternatives and tradeoffs"), ("work", "Implementation work"),
                               ("verification", "Verification obligations"), ("unresolved", "Unresolved"),
                               ("evidence", "Evidence")):
                items = r.get(key)
                if not items:
                    continue
                b += f"## {title}\n\n"
                b += (f"{self._render_ref(items.strip())}\n\n" if isinstance(items, str)
                      else "\n".join(f"- {self._render_ref(str(i))}" for i in items) + "\n\n")
            s = r["status"]
            b += "## Status\n\n" + "\n".join(f"- {k}: {v}" for k, v in s.items()) + "\n"
            self.put(f"70-Requests/{slug(r['id'])}.md", b, generated=False)

    # -- 80 unresolved -----------------------------------------------------------------
    def question_notes(self) -> None:
        b = fm(type="index") + "# Unresolved questions and engineering requirements\n\n"
        b += "| id | kind | status | affects |\n|---|---|---|---|\n"
        for q in sorted(self.questions, key=lambda q: (q["status"], q["kind"], q["id"])):
            b += f"| {link('80-Unresolved/' + slug(q['id']), q['id'])} | {q['kind']} | {q['status']} | {', '.join(self._render_ref(a) for a in q['affects'][:3])} |\n"
        self.put("80-Unresolved/_index.md", b)
        for q in self.questions:
            b = fm(type="question", id=q["id"], kind=q["kind"], status=q["status"]) + f"# {q['id']}\n\n"
            b += f"**Question.** {self._render_ref(q['question'].strip())}\n\n**Kind.** `{q['kind']}` -- **Status.** {q['status']}\n\n"
            b += f"**Why it matters.** {self._render_ref(q['why_it_matters'].strip())}\n\n"
            b += "**Affects.** " + ", ".join(self._render_ref(a) for a in q["affects"]) + "\n\n"
            b += "**Evidence already available.**\n" + "".join(f"- {self._render_ref(e)}\n" for e in q["evidence_available"]) + "\n"
            b += f"**Best remaining source.** {self._render_ref(q['best_remaining_source'])}\n\n"
            b += f"**Procedure.** {self._render_ref(q['procedure'].strip())}\n\n**Done when.** {self._render_ref(q['completion_condition'].strip())}\n\n"
            b += "**Conclusions affected while open.**\n" + "".join(f"- {self._render_ref(c)}\n" for c in q["conclusions_affected_while_open"])
            if q.get("resolved_by"):
                b += f"\n**Resolved by.** {self._render_ref(str(q['resolved_by']).strip())}\n"
            self.put(f"80-Unresolved/{slug(q['id'])}.md", b, generated=False)

    # -- 90 coverage ----------------------------------------------------------------------
    def coverage(self) -> None:
        hooked = self.hooked_types()
        sc = self.surface["counts"]
        pk = self.surface["packages"]
        depth4 = sorted({".".join(p.split(".")[:4]) for p in pk})
        hooked_pkgs = {pkg_of(t) for t in hooked}
        modules = self.fabric["modules"]
        api_with_members = sum(len(m["api"]) for m in modules)
        rb = self.edges["resolution_by_relation"]
        b = fm(type="coverage", generated_at=self.edges["generated_at"]) + "# Coverage, with denominators\n\n"
        b += ("Seven separate measures. None of them is 'supported'. A capability record, a linked "
              "note, or a passing schema establishes nothing about behaviour.\n\n")
        b += "## 1. Surface inventory\n\n"
        b += f"- artifacts classified: {len(self.corpus['artifacts'])} / {len(self.corpus['artifacts'])} (0 unclassified); groups {json.dumps(self.corpus['groups'])}\n"
        b += (f"- classes in the processed compile jar: {sc['classes']} ({sc['top_level']} top-level) in {sc['packages']} packages, "
              f"{sc['members']} declared members -- all inventoried (`extracted:minecraft_surface.json.gz`)\n")
        b += f"- depth-4 packages: {len(depth4)}; with at least one Fabric API hook: {len(hooked_pkgs)}\n"
        b += f"- data pack entry types inventoried: {len(self.corpus['minecraft']['data_entries_by_type'])} (from the jar)\n"
        b += f"- Fabric API modules inventoried: {len(modules)} / {self.corpus['groups'].get('fabric_api_module')}\n"
        env = self.env
        b += (f"- resolved environment recorded: compile {env['counts'].get('compileClasspath')}, runtime {env['counts'].get('runtimeClasspath')}, "
              f"test {env['counts'].get('testRuntimeClasspath')} entries, all hashed; processed-vs-cache jar diff: "
              f"{env['minecraft_jar_processing']['classes_with_different_bytes']} classes\n\n")
        b += "## 2. Extraction\n\n"
        n_declared = sum(m["counts"]["mixin_classes_declared"] for m in modules)
        n_found = sum(m["counts"]["mixin_classes_found"] for m in modules)
        n_fail = sum(m["counts"]["extraction_failures"] for m in modules)
        inj_kinds = collections.Counter(e["injector"] for e in self.injection_edges())
        b += f"- mixin classes: {n_found} found by annotation / {n_declared} declared in configs; extraction failures: {n_fail}\n"
        b += f"- injections: {sum(inj_kinds.values())} by injector {json.dumps(dict(inj_kinds.most_common()))}\n"
        b += f"- Fabric API classes with public surface extracted: {api_with_members} / {sum(m['counts']['api_classes'] for m in modules)}\n"
        b += f"- vanilla types that are hook targets: {len(hooked)}; every one has its declared members in the surface\n\n"
        b += "## 3. Workflow information\n\n"
        areas = collections.Counter(w["area"] for w in self.workflows)
        b += f"- workflow families authored: {len(self.workflows)} across {len(areas)} / 8 areas: {dict(areas)}\n"
        b += f"- families with interaction analysis: {sum(1 for w in self.workflows if w['status']['interaction_analysed'])} / {len(self.workflows)}\n\n"
        b += "## 4. Interaction contracts\n\n"
        b += f"- typed edges: {len(self.edges['edges'])} -- by relation {json.dumps(self.edges['counts'])}\n"
        b += f"- by evidence class: {json.dumps(self.edges['evidence_classes'])}\n"
        b += f"- resolution of injection selectors: injects_into {json.dumps(rb.get('injects_into'))}; wraps {json.dumps(rb.get('wraps'))}; replaces {json.dumps(rb.get('replaces'))}\n"
        b += f"- resolution of injection points (@At): {json.dumps(self.edges['injection_point_resolution'])}\n"
        b += f"- resolution of calls / reads / writes: {json.dumps(rb.get('calls'))} / {json.dumps(rb.get('reads'))} / {json.dumps(rb.get('writes'))}\n"
        b += f"- events with an identified publisher: {sum(1 for v in self.events().values() if v['publishers'])} / {len(self.events())}\n"
        b += f"- events with an analyst-stated subscriber contract: {sum(1 for c in self.contracts if c['kind'] == 'event')} / {len(self.events())}\n"
        b += f"- shared targets (potential interactions, no verdict): {len(self.edges['shared_targets'])}; same-point overlap: not computed\n"
        b += f"- curated interaction records in the store: {len(self.pack.records('interaction'))}\n\n"
        b += "## 5. Executable analysis (ModCheck)\n\n"
        b += f"- capability records: {len(self.pack.records('capability'))}; failures with a detector: {sum(1 for r in self.pack.records('failure') if (r.get('detector') or {}).get('detectable') == 'yes')} / {len(self.pack.records('failure'))}\n"
        b += ("- static mixin-collision analysis over arbitrary mod jars: NOT implemented (the extractor and resolver exist "
              "under atlas/extract; the jvm inspector does not call them; the required order is index -> exact resolution -> applicability -> composition rule)\n\n")
        b += "## 6. Runtime and transformation evidence\n\n"
        b += "- observed edges: 0. No game has run.\n"
        if self.transform:
            n = len(self.transform["scenarios"])
            ok = sum(1 for s in self.transform["scenarios"] if s["transformed"])
            b += (f"- executed_transformation: {n} scenarios run through the pinned Mixin transformer ({ok} transformed, "
                  f"{n - ok} refused at transformation); transformer evidence, not Minecraft evidence\n\n")
        b += "## 7. Creation / maintenance automation\n\n"
        b += "- deterministic generators: 6 mechanisms (Fabric only); the reference lantern was hand-authored, not generated\n- agent execution: boundary exists, unavailable here\n\n"
        # per-system state
        contract_pkgs: collections.Counter = collections.Counter()
        hs = self.handler_sites()
        for c in self.contracts:
            if not c["id"].startswith("event:"):
                continue
            for p in self.events().get(c["id"][6:], {}).get("publishers", []):
                for e in hs.get((p["from"].get("owner"), p["from"]["id"]), []):
                    contract_pkgs[pkg_of(e["to"]["owner"])] += 1
        system_notes = {s["id"] for s in self.systems}
        req_pkgs: dict[str, list[str]] = collections.defaultdict(list)
        for r in self.requests:
            for a in r["affected_systems"]:
                for pkg in depth4:
                    if a.startswith(pkg + " ") or a.startswith(pkg + "."):
                        req_pkgs[pkg].append(r["id"] + ("" if r["status"]["implemented"] == "none" else " (implemented, hand-authored)"))
        b += ("## Per-system state\n\nColumns are independent: *inventoried* = every class and member of the package is in the surface; "
              "*inspected* = hooked types with their edges resolved; *contract-mapped* = analyst contracts whose publication site is in the package; "
              "*analysed* = an analyst system note exists; *in ModCheck* = a request analysis names it; *validated* = the validation scope of that implementation.\n\n"
              "| package | inventoried | inspected | contract-mapped | analysed | in ModCheck | validated |\n|---|---|---|---|---|---|---|\n")
        for pkg in sorted(set(depth4) | system_notes):
            n_types = sum(1 for t in hooked if pkg_of(t) == pkg)
            inspected = f"{n_types} hooked types, edges resolved" if n_types else "no hooks"
            cm = f"{contract_pkgs[pkg]} contracts" if contract_pkgs.get(pkg) else "no"
            an = "system note" if pkg in system_notes else ("edges only" if n_types else "no")
            reqs = req_pkgs.get(pkg, [])
            inm = "; ".join(reqs) if reqs else "no"
            val = "JUnit with fakes, gradle build; no game run" if any("implemented" in r for r in reqs) else "none"
            b += f"| `{pkg}` | all classes | {inspected} | {cm} | {an} | {inm} | {val} |\n"
        self.put("90-Coverage/_index.md", self._render_ref(b))

    # -- index -----------------------------------------------------------------------------
    def index(self) -> None:
        b = fm(type="index") + "# Minecraft Engineering Atlas\n\n"
        b += ("Java Edition 26.3, Fabric loader 0.19.5, Fabric API 0.161.0+26.3 -- the corpus this "
              "project resolved and built against. Other editions, loaders and surfaces are "
              "enumerated as branches, not silently folded in.\n\n"
              f"- {link('00-Scope/Corpus')} · {link('00-Scope/Processed_Jar_Diff')} · {link('00-Scope/Branches')} · {link('00-Scope/Data_Driven_Surface')} · {link('00-Scope/Sources')}\n"
              f"- {link('10-Workflows/_index', 'Workflows and request families')}\n"
              f"- {link('20-Systems/_index', 'Game systems (full inventory)')}\n"
              f"- {link('30-Mechanisms/_index', 'Modification mechanisms')} · {link('30-Mechanisms/Transformation_Tests', 'Transformation tests')}\n"
              f"- {link('40-Interfaces/_index', 'Exact interfaces')}\n"
              f"- {link('50-Interactions/_index', 'Interaction contracts')} · {link('50-Interactions/shared_targets', 'Shared targets')}\n"
              f"- {link('60-Failures/_index', 'Known failures')}\n"
              f"- {link('70-Requests/_index', 'Request impact analyses')}\n"
              f"- {link('80-Unresolved/_index', 'Unresolved questions')}\n"
              f"- {link('90-Coverage/_index', 'Coverage')}\n\n"
              "## Reading the labels\n\n"
              "`direct_reference` was read from a class file. `static_inference` is a bytecode pattern. "
              "`declared` is a manifest or a signature. `documented` is cached prose. `executed_transformation` is the "
              "pinned Mixin transformer run over controlled classes in a plain JVM. `observed` would be a running "
              "game, and nothing is.\n")
        self.put("_index.md", b)
        for path in AUTHORED.rglob("*.md"):
            rel = path.relative_to(AUTHORED)
            self.put(f"_authored/{rel}", fm(type="authored", source=str(path.relative_to(ROOT))) + self._render_ref(path.read_text()), generated=False)


def main() -> int:
    atlas = Atlas()
    atlas.build()
    print(f"vault: {len(atlas.written)} notes under {VAULT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
