"""Parsing Content Patcher's diagnostics, and judging predictions against them.

What these tests establish, and what they do not:

* They establish that the parser reads the format Content Patcher's own code
  emits. The transcripts below are generated by `_summary`/`_dump_*`, which
  reproduce the C# format strings from SummaryCommand.cs and DumpCommand.cs at
  Pathoschild/StardewMods 76565e83ede4bc8b3c293f1c659032ba9c39c213 -- including
  the runtime-computed column widths, which is the part a hand-typed sample
  gets wrong.
* They do NOT establish that a real game emitted any of this. That is game
  evidence, the top tier, and it requires the licensed installation. Nothing
  here may be cited as observation.

The second half tests the thing the predictions exist for: that a transcript
disagreeing with a prediction is reported as a contradiction rather than
absorbed into a narrative that fits.
"""
from __future__ import annotations

from modcheck.observe import (compare, contentpatcher as cp,
                              load_predictions, parse_dump_applied,
                              parse_dump_order, parse_summary)
from modcheck.paths import project_root

PREDICTIONS = project_root() / "evaluation" / "runtime" / "predictions"


def _summary(mod: str, rows: list[dict], changes: dict[str, list[str]] | None = None) -> str:
    """Reproduce the `patch summary` tables, padding included."""
    width = max(len("priority"), max((len(r.get("priority") or "") for r in rows), default=0))
    out = [
        "=====================",
        "== Content patches ==",
        "=====================",
        "The following patches were loaded. For each patch:",
        "",
        f"{mod}:",
        "-" * (len(mod) + 1),
        "",
        "   Patches:",
        f"      loaded  | conditions | applied | {'priority'.ljust(width)} | name + details",
        f"      ------- | ---------- | ------- | {'-' * width} | --------------",
    ]
    for row in rows:
        box = lambda key: "X" if row.get(key) else " "  # noqa: E731
        line = (f"      [{box('loaded')}]     | [{box('conditions')}]        | "
                f"[{box('applied')}]     | {(row.get('priority') or '').ljust(width)} | "
                f"{row['name']}")
        if row.get("resolved"):
            line += f" ({row.get('raw', '')} => {row['resolved']})".replace("( =>", "(=>")
        if row.get("locale"):
            line += f" (locale: {row['locale']} only)"
        if row.get("reason"):
            line += f"  // {row['reason']}"
        for hint in row.get("hints", []):
            line += f" // hint: {hint}"
        out.append(line)
    out.append("")
    if changes:
        asset_width = max(len("asset name"), max(len(k) for k in changes))
        out.append("   Current changes:")
        out.append(f"      {'asset name'.ljust(asset_width)} | changes")
        out.append(f"      {'-' * asset_width} | -------")
        for target, labels in changes.items():
            out.append(f"      {target.ljust(asset_width)} | {'; '.join(labels)}")
    else:
        out.append("   No current changes.")
    out.append("")
    return "\n".join(out)


BASELINE_ROWS = [
    {"name": "entry #1 > The Bear", "loaded": True, "conditions": True, "applied": True,
     "priority": "Exclusive", "raw": "Load Animals/horse", "resolved": "Animals/horse"},
    {"name": "entry #2 > Spirit's Eve Special", "loaded": True, "conditions": False,
     "applied": False, "priority": "Default"},
    {"name": "entry #3 > Saddle Overlay", "loaded": True, "conditions": False,
     "applied": False, "priority": "Default"},
    {"name": "entry #5 > Male Farmer Reins", "loaded": True, "conditions": True,
     "applied": True, "priority": "Default"},
    {"name": "entry #12 > Stable overlay", "loaded": True, "conditions": True,
     "applied": True, "priority": "Default"},
]


def test_a_patch_row_is_read_field_by_field():
    summary = parse_summary(_summary("Bear Mounts", BASELINE_ROWS))
    bear = summary.patches[0]
    assert bear.mod == "Bear Mounts"
    assert bear.name == "entry #1 > The Bear"
    assert (bear.loaded, bear.conditions_match, bear.applied) == (True, True, True)
    assert bear.priority == "Exclusive"
    assert bear.resolved_target == "Animals/horse"
    assert bear.raw_target == "Animals/horse"  # the "Load " prefix is stripped


def test_an_unchecked_box_is_false_not_missing():
    summary = parse_summary(_summary("Bear Mounts", BASELINE_ROWS))
    saddle = next(p for p in summary.patches if "Saddle" in p.name)
    assert saddle.loaded is True
    assert saddle.conditions_match is False
    assert saddle.applied is False


def test_the_priority_column_is_read_at_any_width():
    """The width is computed from the widest value, so it varies per run."""
    narrow = parse_summary(_summary("M", [dict(BASELINE_ROWS[1])]))
    wide = parse_summary(_summary("M", [
        dict(BASELINE_ROWS[1]), {"name": "x", "loaded": True, "conditions": True,
                                 "applied": True, "priority": "Exclusive + 12345"}]))
    assert narrow.patches[0].priority == "Default"
    assert wide.patches[0].priority == "Default"
    assert wide.patches[1].priority == "Exclusive + 12345"


def test_a_reason_and_a_hint_are_kept_apart():
    text = _summary("M", [{
        "name": "entry #1 > Broken", "loaded": False, "conditions": False, "applied": False,
        "priority": "Exclusive", "reason": "the FromFile 'assets/nope.png' doesn't exist",
        "hints": ["asset name may be incorrect (shouldn't include 'Content/' prefix)."]}])
    patch = parse_summary(text).patches[0]
    assert patch.name == "entry #1 > Broken"
    assert patch.reason_not_loaded == "the FromFile 'assets/nope.png' doesn't exist"
    assert patch.hints == ["asset name may be incorrect (shouldn't include 'Content/' prefix)."]


def test_current_changes_are_read_per_target():
    summary = parse_summary(_summary(
        "Bear Mounts", BASELINE_ROWS,
        {"Animals/horse": ["loaded assets/BearMount_brown.png"],
         "Buildings/Stable": ["edited image"]}))
    section = summary.mod("Bear Mounts")
    assert section is not None
    assert section.current_changes["Animals/horse"] == ["loaded assets/BearMount_brown.png"]
    assert section.no_current_changes is False


def test_no_current_changes_is_recorded_as_such():
    section = parse_summary(_summary("Bear Mounts", BASELINE_ROWS)).mod("Bear Mounts")
    assert section is not None
    assert section.no_current_changes is True
    assert section.current_changes == {}


DUMP_APPLIED = """Here are the active patches grouped by their current target value.

Animals/horse
-------------
   [X] Load Bear Mounts > entry #1 > The Bear
   [ ] EditImage Bear Mounts > entry #3 > Saddle Overlay

Buildings/Stable
----------------
   [X] EditImage Bear Mounts > entry #12 > Stable overlay
"""


def test_dump_applied_groups_by_target_in_apply_order():
    dump = parse_dump_applied(DUMP_APPLIED)
    assert list(dump.by_target) == ["Animals/horse", "Buildings/Stable"]
    assert dump.order_for("Animals/horse") == [
        "Bear Mounts > entry #1 > The Bear", "Bear Mounts > entry #3 > Saddle Overlay"]
    assert dump.applied_for("Animals/horse") == ["Bear Mounts > entry #1 > The Bear"]
    assert dump.by_target["Animals/horse"][0][1] == "Load"


DUMP_ORDER = """Here's the global patch definition order across all loaded content packs.

   order   index path   patch
   -----   ----------   -----
   1       0/0          Bear Mounts > entry #1 > The Bear
   2       0/1          Bear Mounts > entry #2 > Spirit's Eve Special
   3       1/0          ModCheck Conflict Probe > entry #1 > Probe Horse
"""


def test_dump_order_is_read_as_a_sequence():
    dump = parse_dump_order(DUMP_ORDER)
    assert len(dump.rows) == 3
    assert dump.rows[0] == ("1", "0/0", "Bear Mounts > entry #1 > The Bear")
    assert dump.position_of("Probe Horse") == 2
    assert dump.position_of("nothing here") is None


# -- judging predictions ----------------------------------------------------

def _prediction(case_id: str):
    return next(p for p in load_predictions(PREDICTIONS) if p.id == case_id)


def test_every_prediction_is_still_unobserved():
    """The runtime half of the loop is blocked, and the records must say so."""
    for prediction in load_predictions(PREDICTIONS):
        assert prediction.observation_status in ("not_yet_observed", "blocked"), (
            f"{prediction.id} claims an observation; a transcript must be committed "
            "alongside any such claim")


def test_a_matching_transcript_matches():
    comparison = compare(_prediction("sv_baseline_bear_mounts"),
                         parse_summary(_summary("Bear Mounts", BASELINE_ROWS)))
    assert comparison.verdict == "matched", [
        (r.claim.describe(), r.verdict, r.observed) for r in comparison.results
        if not r.matched]


def test_a_transcript_that_disagrees_is_reported_as_contradicted():
    """The test that makes the whole exercise worth doing."""
    rows = [dict(row) for row in BASELINE_ROWS]
    rows[0]["priority"] = "High"  # the summary says High where we predicted Exclusive
    comparison = compare(_prediction("sv_baseline_bear_mounts"),
                         parse_summary(_summary("Bear Mounts", rows)))
    assert comparison.verdict == "contradicted"
    wrong = [r for r in comparison.results if r.verdict == "contradicted"]
    assert any("patch_priority" in r.claim.kind for r in wrong)


def test_a_claim_the_transcript_cannot_answer_is_not_a_pass():
    comparison = compare(_prediction("sv_conditional_behaviour"),
                         parse_summary(_summary("Bear Mounts", [
                             {"name": "entry #3 > Saddle Overlay", "loaded": True,
                              "conditions": True, "applied": True, "priority": "Default"},
                             {"name": "entry #1 > The Bear", "loaded": True,
                              "conditions": True, "applied": True, "priority": "Exclusive"},
                             {"name": "entry #2 > Spirit's Eve Special", "loaded": True,
                              "conditions": False, "applied": False, "priority": "Default"},
                         ])))
    # Every summary-answerable claim matches, but apply_order needs a dump.
    assert comparison.verdict == "incomplete"
    unobserved = [r for r in comparison.results if r.verdict == "unobserved"]
    assert [r.claim.kind for r in unobserved] == ["apply_order"]


def test_supplying_the_dump_completes_it():
    comparison = compare(
        _prediction("sv_conditional_behaviour"),
        parse_summary(_summary("Bear Mounts", [
            {"name": "entry #3 > Saddle Overlay", "loaded": True, "conditions": True,
             "applied": True, "priority": "Default"},
            {"name": "entry #1 > The Bear", "loaded": True, "conditions": True,
             "applied": True, "priority": "Exclusive"},
            {"name": "entry #2 > Spirit's Eve Special", "loaded": True,
             "conditions": False, "applied": False, "priority": "Default"},
        ])),
        applied=parse_dump_applied(
            "Animals/horse\n-------------\n"
            "   [X] Load Bear Mounts > entry #1 > The Bear\n"
            "   [X] EditImage Bear Mounts > entry #3 > Saddle Overlay\n"))
    assert comparison.verdict == "matched"


def test_a_reversed_apply_order_is_contradicted():
    comparison = compare(
        _prediction("sv_conditional_behaviour"),
        parse_summary(_summary("Bear Mounts", [
            {"name": "entry #3 > Saddle Overlay", "loaded": True, "conditions": True,
             "applied": True, "priority": "Default"},
            {"name": "entry #1 > The Bear", "loaded": True, "conditions": True,
             "applied": True, "priority": "Exclusive"},
            {"name": "entry #2 > Spirit's Eve Special", "loaded": True,
             "conditions": False, "applied": False, "priority": "Default"},
        ])),
        applied=parse_dump_applied(
            "Animals/horse\n-------------\n"
            "   [X] EditImage Bear Mounts > entry #3 > Saddle Overlay\n"
            "   [X] Load Bear Mounts > entry #1 > The Bear\n"))
    assert comparison.verdict == "contradicted"


def test_the_conflict_prediction_needs_both_loads_unapplied():
    """Predicting 'neither applies' must fail if either one does."""
    prediction = _prediction("sv_deliberate_conflict")
    neither = _summary("Bear Mounts", [
        {"name": "entry #1 > The Bear", "loaded": True, "conditions": True,
         "applied": False, "priority": "Exclusive"},
        {"name": "entry #1 > Probe Horse", "loaded": True, "conditions": True,
         "applied": False, "priority": "Exclusive"}])
    assert compare(prediction, parse_summary(neither)).verdict == "matched"

    one_won = neither.replace("[ ]     | Exclusive | entry #1 > The Bear",
                              "[X]     | Exclusive | entry #1 > The Bear")
    assert one_won != neither
    assert compare(prediction, parse_summary(one_won)).verdict == "contradicted"


def test_inputs_are_rehashed_before_a_prediction_is_judged():
    """A prediction retargeted at different bytes is not the same prediction."""
    prediction = _prediction("sv_baseline_bear_mounts")
    problems = [item.verify(project_root()) for item in prediction.inputs]
    for problem in problems:
        assert problem is None or "not present" in problem, problem


def test_the_priority_model_matches_the_priority_the_runtime_prints():
    """Our analyzer's labels are the ones `patch summary` shows, or comparison lies."""
    from modcheck.analyze import contentpatcher as analyze_cp
    assert analyze_cp.parse_load_priority(None).raw == "Exclusive"
    assert analyze_cp.parse_load_priority("High").value == 1000
    assert analyze_cp.parse_edit_priority(None).raw == "Default"
    assert analyze_cp.parse_edit_priority("Late + 5").value == 1005
    # SMAPI's AssetLoadPriority.Exclusive is int.MaxValue, so no numeric priority
    # can outrank it. Our resolver must treat Exclusive as a kind, never a number.
    assert analyze_cp.parse_load_priority("Exclusive").value is None
    assert analyze_cp.parse_load_priority("Exclusive").is_exclusive
