"""Deterministic generators, one per recorded mechanism.

What this is, stated precisely, because the distinction matters more than the
code: these emit the *wiring* a mechanism requires -- the registration call,
the type the API expects, the entrypoint entry, the payload plumbing -- derived
from the capability record that establishes the mechanism. They do not write a
creator's domain logic, and they do not invent an API.

**There is no model invocation anywhere in ModCheck.** Nothing here calls a
language model, and the product cannot synthesise arbitrary novel code. What it
does is compose recorded mechanisms into a reviewable diff, leave a clearly
marked seam where the creator's own logic goes, and refuse when the mechanism
is not grounded.

One generator per *mechanism*, never one per demonstration. Three different
requests reuse the same four generators in different combinations; a genuinely
new mechanism needs a new generator, and `plan` says so rather than pretending
otherwise.

Every generator takes the capability record it implements and cites it in the
emitted file, so a reader can trace a line of generated code back to the
signature that justified it and the artifact hash that signature came from.
"""
from __future__ import annotations

import dataclasses
import json
import re
from pathlib import Path
from typing import Any

from ..store import Record, Store
from .apply import ApplyError, ChangeSet, FileChange, _fabric_manifest_path, _load_manifest

# Where a creator's own logic goes. Emitted code marks the seam explicitly; a
# generator that silently produced an empty method body would be presenting a
# placeholder as a finished feature.
SEAM = "// >>> your logic here"


@dataclasses.dataclass
class Emission:
    """One generated file, with the evidence that justified it."""
    path: str
    content: str
    cites: list[str]


def _package_of(root: Path) -> str:
    """The mod's base package, read from its declared main entrypoint."""
    _, manifest = _load_manifest(root)
    entrypoints = (manifest.get("entrypoints") or {})
    for kind in ("main", "client", "server"):
        for entry in entrypoints.get(kind, []):
            value = entry if isinstance(entry, str) else entry.get("value", "")
            if "." in value:
                return value.rsplit(".", 1)[0]
    raise ApplyError(
        "cannot infer the mod's package: fabric.mod.json declares no entrypoint "
        "with a qualified class name. Add a main entrypoint first "
        "(`modcheck apply fabric.add_entrypoint`).")


def _mod_id(root: Path) -> str:
    _, manifest = _load_manifest(root)
    mod_id = manifest.get("id")
    if not mod_id:
        raise ApplyError("fabric.mod.json declares no id")
    return str(mod_id)


def _java_name(text: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", text)
    return "".join(p[:1].upper() + p[1:] for p in parts if p) or "Generated"


def _header(record: Record, extra: str = "") -> str:
    """The provenance banner every generated file carries."""
    lines = [
        "// Generated by ModCheck from capability record "
        f"{record.game}/{record.id}.",
        "//",
        "// The signatures below were read from the artifact that record cites, not",
        "// from documentation. Re-check them with:",
        f"//   modcheck show {record.id} --game {record.game}",
    ]
    for reference in (record.get("references") or [])[:3]:
        quote = reference.get("quote")
        lines.append(f"//   {reference.get('source')}: {quote or reference.get('locator')}")
    if extra:
        lines.append("//")
        for line in extra.strip().splitlines():
            lines.append(f"// {line}")
    return "\n".join(lines)


def _source_path(package: str, class_name: str) -> str:
    return f"src/main/java/{package.replace('.', '/')}/{class_name}.java"


# --- one generator per recorded mechanism --------------------------------

def gamerule(root: Path, record: Record, *, name: str, default: int,
             minimum: int = 1, maximum: int = 100000) -> Emission:
    """add_configuration via a custom gamerule."""
    package = _package_of(root)
    mod_id = _mod_id(root)
    class_name = f"{_java_name(name)}Rules"
    field = re.sub(r"(?<!^)(?=[A-Z])", "_", _java_name(name)).upper()
    rule_id = re.sub(r"[^a-z0-9_]+", "_", name.lower())
    content = f"""{_header(record, '''
GameRuleRegistry and GameRuleFactory do not exist in this Fabric API version.
The builder below is what the resolved jar actually declares.''')}
package {package};

import net.fabricmc.fabric.api.gamerule.v1.GameRuleBuilder;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.gamerules.GameRule;
import net.minecraft.world.level.gamerules.GameRuleCategory;

public final class {class_name} {{
    /** Operators change this with: /gamerule {mod_id}:{rule_id} <value> */
    public static final GameRule<Integer> {field} = GameRuleBuilder
            .forInteger({default})
            .category(GameRuleCategory.MISC)
            .buildAndRegister(Identifier.fromNamespaceAndPath("{mod_id}", "{rule_id}"));

    private {class_name}() {{
    }}

    /**
     * Registration happens by class initialisation, so this must be called from
     * mod init -- before any world loads. A rule registered later is absent
     * from worlds already running.
     */
    public static void register() {{
        // Touching the class is what runs the static initialiser above.
    }}

    /** Declared range, for the creator's own clamping: {minimum}..{maximum}. */
    public static int clamp(int value) {{
        return Math.max({minimum}, Math.min({maximum}, value));
    }}
}}
"""
    return Emission(_source_path(package, class_name), content,
                    [f"{record.game}/{record.id}"])


def saved_data(root: Path, record: Record, *, name: str,
               field_name: str = "charge") -> Emission:
    """persist_state via SavedData with a codec."""
    package = _package_of(root)
    mod_id = _mod_id(root)
    class_name = f"{_java_name(name)}State"
    store_id = re.sub(r"[^a-z0-9_]+", "_", name.lower())
    content = f"""{_header(record, '''
This version serialises through a Codec, not through load/save(CompoundTag).
setDirty() after every mutation: SavedDataStorage writes only instances marked
dirty, and a change that skips it is lost on reload with no error anywhere.''')}
package {package};

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.datafix.DataFixTypes;
import net.minecraft.world.level.saveddata.SavedData;
import net.minecraft.world.level.saveddata.SavedDataType;

public class {class_name} extends SavedData {{
    public static final Codec<{class_name}> CODEC = RecordCodecBuilder.create(instance ->
            instance.group(
                    Codec.INT.fieldOf("{field_name}").forGetter({class_name}::get{_java_name(field_name)})
            ).apply(instance, {class_name}::new));

    public static final SavedDataType<{class_name}> TYPE = new SavedDataType<>(
            Identifier.fromNamespaceAndPath("{mod_id}", "{store_id}"),
            {class_name}::new,
            CODEC,
            DataFixTypes.LEVEL);

    private int {field_name};

    public {class_name}() {{
        this(0);
    }}

    public {class_name}(int {field_name}) {{
        this.{field_name} = {field_name};
    }}

    public int get{_java_name(field_name)}() {{
        return this.{field_name};
    }}

    public void set{_java_name(field_name)}(int value) {{
        this.{field_name} = value;
        // Without this the value is held in memory and never written.
        this.setDirty();
    }}

    /** Per level, not per server: two dimensions hold independent values. */
    public static {class_name} get(ServerLevel level) {{
        return level.getDataStorage().computeIfAbsent(TYPE);
    }}
}}
"""
    return Emission(_source_path(package, class_name), content,
                    [f"{record.game}/{record.id}"])


def server_tick(root: Path, record: Record, *, name: str,
                state_class: str, rule_class: str | None = None) -> Emission:
    """subscribe_event via ServerTickEvents, with the creator's seam marked."""
    package = _package_of(root)
    class_name = f"{_java_name(name)}Ticker"
    rule_import = f"\n// rule: {rule_class}" if rule_class else ""
    # GameRules exposes a single generic get(GameRule<T>); there is no getInt.
    rule_field = re.sub(r"(?<!^)(?=[A-Z])", "_", _java_name(name)).upper()
    rule_read = (f"int rate = {rule_class}.clamp(level.getGameRules().get({rule_class}."
                 f"{rule_field}));" if rule_class else "int rate = 1;")
    content = f"""{_header(record, '''
END_LEVEL_TICK carries the ServerLevel, which per-level state and per-level
weather both need; END_SERVER_TICK does not. The name is END_LEVEL_TICK in this
version, not the END_WORLD_TICK of older Fabric APIs. This runs on the server thread:
blocking here stalls the tick loop for every player.''')}{rule_import}
package {package};

import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.minecraft.server.level.ServerLevel;

public final class {class_name} {{
    private {class_name}() {{
    }}

    public static void register() {{
        ServerTickEvents.END_LEVEL_TICK.register({class_name}::onLevelTick);
    }}

    private static void onLevelTick(ServerLevel level) {{
        {state_class} state = {state_class}.get(level);
        {rule_read}

        {SEAM}
        // ModCheck generated the subscription, the level-scoped access and the
        // state lookup. What counts as a tick worth acting on -- and what the
        // action is -- is yours: this method currently does nothing with `state`
        // or `rate`, and that is deliberate rather than an oversight.
    }}
}}
"""
    return Emission(_source_path(package, class_name), content,
                    [f"{record.game}/{record.id}"])


def sync_payload(root: Path, record: Record, *, name: str,
                 field_name: str = "charge") -> Emission:
    """sync_state via a CustomPacketPayload registered for play S2C."""
    package = _package_of(root)
    mod_id = _mod_id(root)
    class_name = f"{_java_name(name)}Payload"
    payload_id = re.sub(r"[^a-z0-9_]+", "_", name.lower())
    content = f"""{_header(record, '''
The payload type must be registered on BOTH sides. A type registered only on
the server is not decodable by a client, and canSend() reports false for a
client that lacks it -- sending anyway is an error, not a no-op.''')}
package {package};

import io.netty.buffer.ByteBuf;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.resources.Identifier;

public record {class_name}(int {field_name}) implements CustomPacketPayload {{
    public static final CustomPacketPayload.Type<{class_name}> TYPE =
            new CustomPacketPayload.Type<>(
                    Identifier.fromNamespaceAndPath("{mod_id}", "{payload_id}"));

    public static final StreamCodec<ByteBuf, {class_name}> CODEC =
            StreamCodec.composite(
                    ByteBufCodecs.VAR_INT, {class_name}::{field_name},
                    {class_name}::new);

    @Override
    public CustomPacketPayload.Type<{class_name}> type() {{
        return TYPE;
    }}
}}
"""
    return Emission(_source_path(package, class_name), content,
                    [f"{record.game}/{record.id}"])


def hud_element(root: Path, record: Record, *, name: str, payload_class: str,
                field_name: str = "charge") -> Emission:
    """display_information via a registered HUD element."""
    package = _package_of(root)
    mod_id = _mod_id(root)
    class_name = f"{_java_name(name)}Hud"
    element_id = re.sub(r"[^a-z0-9_]+", "_", name.lower())
    content = f"""{_header(record, '''
HudRenderCallback is not what this Fabric API version exposes. Client-side
only: this cannot read server SavedData, which is why it renders a value the
server sent rather than one it looks up.''')}
package {package};

import net.fabricmc.fabric.api.client.rendering.v1.hud.HudElementRegistry;
import net.fabricmc.fabric.api.client.rendering.v1.hud.VanillaHudElements;
import net.minecraft.resources.Identifier;

public final class {class_name} {{
    /** Updated by the payload handler; the client has no other copy. */
    private static volatile int lastKnownValue = 0;

    private {class_name}() {{
    }}

    public static void accept({payload_class} payload) {{
        lastKnownValue = payload.{field_name}();
    }}

    public static int lastKnownValue() {{
        return lastKnownValue;
    }}

    public static void register() {{
        // Attached after a named vanilla element rather than added last, so the
        // position does not depend on what other mods have registered.
        HudElementRegistry.attachElementAfter(
                VanillaHudElements.HOTBAR,
                Identifier.fromNamespaceAndPath("{mod_id}", "{element_id}"),
                (context, tickCounter) -> {{
                    {SEAM}
                    // ModCheck generated the registration and the value holder.
                    // What to draw, and where, is yours -- nothing is drawn yet.
                }});
    }}
}}
"""
    return Emission(_source_path(package, class_name), content,
                    [f"{record.game}/{record.id}"])


# Keyed by the capability the record answers, so a plan selects a generator by
# the same id it used to select the mechanism. A capability with no entry here
# is one the product can plan but not wire, and `for_capability` says so.
BY_CAPABILITY = {
    "add_configuration": gamerule,
    "persist_state": saved_data,
    "subscribe_event": server_tick,
    "sync_state": sync_payload,
    "display_information": hud_element,
}


def for_capability(capability: str):
    return BY_CAPABILITY.get(capability)
